backend:
  name: github
  repo: vovasprut/rental-site
  branch: main
  site_id: 25cc333b-02bf-414f-949a-ec4338fe8959

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "items"
    label: "Товары"
    folder: "items"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "text" }
      - { label: "Цена", name: "price", widget: "string" }
      - { label: "Изображение", name: "image", widget: "image" }
